### ISSUE TITLE
Importing submissions with SIDs doesn't work

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/webform_import#7] opened 2023-08-15 03:38 UTC
The existing code doesn't work when you want to insert an exported form submission, which of course contains an SID, into a site that doesn't have that submission already. This defeats the purpose of having an import capability, i.e. to bring in webform submissions that don't yet exist.

The current functionality might be useful on a subsequent import, as it will not create a new submission for existing entries, but instead try to update them. If the code merely overwrites the existing submissions, that should still be OK though.

I did some digging into the code since I was already working on it, and found the cause of the problem. Here is the code so it's clear what I mean: 
```
      // Determine if INSERT or UPDATE based on inclusion of SID.
      if ($sid != NULL) {
        $submission->sid = $sid;
        $sids[] = webform_submission_update($webform, $submission);
      }
      else {
        $sids[] = webform_submission_insert($webform, $submission);
      }
```

The `webform_submission_update` function (called if there is an SID) does **not** write a new submission to the `webform_submissions` table but only updates it IF there is already an entry in the `webform_submissions` table. However, it DOES write new records to the `webform_submitted_data` DB table, creating a mess in the DB as well.

I considered simply using the `webform_submission_insert` function in all cases and this **does** import all the entries, BUT assigns a new SID to each submission.

**Comment by leeksoup** [comment] 2023-11-30 20:28
My PR https://github.com/backdrop-contrib/webform_import/pull/6 has also fixed this problem.

**Comment by jenlampton** [comment] 2024-02-08 00:33
It sounds like this issue may be a duplicate of #4 if that solutuon covers both, so I'm going to close this issue as a duplicate.  Thanks for all your work on this @leeksoup !!! :)

**Closed as completed by jenlampton** 2024-02-08 00:33 UTC
